require 'rspec'
require './lib/turn'
require './lib/card'
require './lib/deck'
require './lib/player'

RSpec.describe Turn do
  it "exists" do
    turn = Turn.new('player1', 'player2')

    expect(turn).to be_an_instance_of(Turn)
  end

  it "has readable attributes" do
    turn = Turn.new('player1', 'player2')

    expect(turn.player1).to eq('player1')
    expect(turn.player2).to eq('player2')
    expect(turn.spoils_of_war).to eq([])
  end

  it "can determine type" do
    turn = Turn.new('player1', 'player2')
    player1 = Player.new('Megan', Deck.new)
    player2 = Player.new('Aurora', Deck.new)
    card1 = Card.new(:heart, 'Jack', 11)
    card2 = Card.new(:heart, '10', 10)
    card3 = Card.new(:heart, '9', 9)
    card4 = Card.new(:diamond, 'Jack', 11)
    card5 = Card.new(:heart, '8', 8)
    card6 = Card.new(:diamond, '8', 8)
    card7 = Card.new(:diamond, 'Queen', 12)
    card8 = Card.new(:heart, '3', 3)
    card9 = Card.new(:diamond, '2', 2)
    card10 = Card.new(:diamond, '3', 3)
    card11 = Card.new(:diamond, '4', 4)
    card12 = Card.new(:diamond, '5', 5)
    card13 = Card.new(:diamond, '6', 6)
    card14 = Card.new(:diamond, '7', 7)
    card15 = Card.new(:diamond, '9', 9)
    card16 = Card.new(:diamond, '10', 10)
    card17 = Card.new(:diamond, 'Jack', 11)
    card18 = Card.new(:diamond, 'Queen', 12)
    card19 = Card.new(:diamond, 'King', 13)
    card20 = Card.new(:diamond, 'Ace', 14)
    player1.deck.add_card(card1)
    player1.deck.add_card(card2)
    player1.deck.add_card(card5)
    player1.deck.add_card(card8)
    player2.deck.add_card(card3)
    player2.deck.add_card(card4)
  end

  it "can determine winner" do
    turn = Turn.new('player1', 'player2')
    player1 = Player.new('Megan', Deck.new)
    player2 = Player.new('Aurora', Deck.new)
    card1 = Card.new(:heart, 'Jack', 11)
    card2 = Card.new(:heart, '10', 10)
    card3 = Card.new(:heart, '9', 9)
    card4 = Card.new(:diamond, 'Jack', 11)
    card5 = Card.new(:heart, '8', 8)
    card6 = Card.new(:diamond, '8', 8)
    card7 = Card.new(:diamond, 'Queen', 12)
    card8 = Card.new(:heart, '3', 3)
    card9 = Card.new(:diamond, '2', 2)
    card10 = Card.new(:diamond, '3', 3)
    card11 = Card.new(:diamond, '4', 4)
    card12 = Card.new(:diamond, '5', 5)
    card13 = Card.new(:diamond, '6', 6)
    card14 = Card.new(:diamond, '7', 7)
    card15 = Card.new(:diamond, '9', 9)
    card16 = Card.new(:diamond, '10', 10)
    card17 = Card.new(:diamond, 'Jack', 11)
    card18 = Card.new(:diamond, 'Queen', 12)
    card19 = Card.new(:diamond, 'King', 13)
    card20 = Card.new(:diamond, 'Ace', 14)
    player1.deck.add_card(card1)
    player1.deck.add_card(card2)
    player1.deck.add_card(card5)
    player1.deck.add_card(card8)
    player2.deck.add_card(card3)
    player2.deck.add_card(card4)
  end

  it "can award spoils" do
    turn = Turn.new('player1', 'player2')
    player1 = Player.new('Megan', Deck.new)
    player2 = Player.new('Aurora', Deck.new)
    card1 = Card.new(:heart, 'Jack', 11)
    card2 = Card.new(:heart, '10', 10)
    card3 = Card.new(:heart, '9', 9)
    card4 = Card.new(:diamond, 'Jack', 11)
    card5 = Card.new(:heart, '8', 8)
    card6 = Card.new(:diamond, '8', 8)
    card7 = Card.new(:diamond, 'Queen', 12)
    card8 = Card.new(:heart, '3', 3)
    card9 = Card.new(:diamond, '2', 2)
    card10 = Card.new(:diamond, '3', 3)
    card11 = Card.new(:diamond, '4', 4)
    card12 = Card.new(:diamond, '5', 5)
    card13 = Card.new(:diamond, '6', 6)
    card14 = Card.new(:diamond, '7', 7)
    card15 = Card.new(:diamond, '9', 9)
    card16 = Card.new(:diamond, '10', 10)
    card17 = Card.new(:diamond, 'Jack', 11)
    card18 = Card.new(:diamond, 'Queen', 12)
    card19 = Card.new(:diamond, 'King', 13)
    card20 = Card.new(:diamond, 'Ace', 14)
    player1.deck.add_card(card1)
    player1.deck.add_card(card2)
    player1.deck.add_card(card5)
    player1.deck.add_card(card8)
    player2.deck.add_card(card3)
    player2.deck.add_card(card4)
  end

  it "can pile cards" do
    turn = Turn.new('player1', 'player2')
    player1 = Player.new('Megan', Deck.new)
    player2 = Player.new('Aurora', Deck.new)
    card1 = Card.new(:heart, 'Jack', 11)
    card2 = Card.new(:heart, '10', 10)
    card3 = Card.new(:heart, '9', 9)
    card4 = Card.new(:diamond, 'Jack', 11)
    card5 = Card.new(:heart, '8', 8)
    card6 = Card.new(:diamond, '8', 8)
    card7 = Card.new(:diamond, 'Queen', 12)
    card8 = Card.new(:heart, '3', 3)
    card9 = Card.new(:diamond, '2', 2)
    card10 = Card.new(:diamond, '3', 3)
    card11 = Card.new(:diamond, '4', 4)
    card12 = Card.new(:diamond, '5', 5)
    card13 = Card.new(:diamond, '6', 6)
    card14 = Card.new(:diamond, '7', 7)
    card15 = Card.new(:diamond, '9', 9)
    card16 = Card.new(:diamond, '10', 10)
    card17 = Card.new(:diamond, 'Jack', 11)
    card18 = Card.new(:diamond, 'Queen', 12)
    card19 = Card.new(:diamond, 'King', 13)
    card20 = Card.new(:diamond, 'Ace', 14)
    player1.deck.add_card(card1)
    player1.deck.add_card(card2)
    player1.deck.add_card(card5)
    player1.deck.add_card(card8)
    player2.deck.add_card(card3)
    player2.deck.add_card(card4)
  end
end